# Generated by Django 4.2.4 on 2024-11-02 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('director', models.CharField(max_length=155, verbose_name='ФИО директора')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies_polygon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контрагент на полигон',
                'verbose_name_plural': 'Контрагенты на полигон',
            },
        ),
    ]
