# Generated by Django 4.2.4 on 2024-11-02 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolygon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies_polygon', to=settings.AUTH_USER_MODEL),
        ),
    ]
