# Generated by Django 4.2.4 on 2024-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0002_alter_companypolygon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolygon',
            name='director',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='ФИО директора'),
        ),
    ]
