# Generated by Django 4.2.4 on 2024-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0003_alter_companypolygon_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolygon',
            name='inn',
            field=models.CharField(max_length=14, verbose_name='ИНН'),
        ),
    ]
