# Generated by Django 4.2.4 on 2024-11-12 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polygon', '0004_alter_companypolygon_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypolygon',
            name='user',
        ),
        migrations.AddField(
            model_name='companypolygon',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies_polygon', to=settings.AUTH_USER_MODEL),
        ),
    ]
