# Generated by Django 4.2.4 on 2024-11-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0005_remove_companypolygon_user_companypolygon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypolygon',
            old_name='user',
            new_name='users',
        ),
    ]
