# Generated by Django 4.2.4 on 2024-03-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='Sample', max_length=155, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
