# Generated by Django 4.2.4 on 2024-03-19 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 18, 29, 25, 543670)),
        ),
    ]
