# Generated by Django 4.2.4 on 2024-03-22 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0005_alter_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 16, 16, 42, 851521), verbose_name='Начало простоя')),
                ('finished_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 16, 16, 42, 851521), verbose_name='Окончание простоя')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Простой',
                'verbose_name_plural': 'Простои',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 16, 16, 42, 850520)),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 16, 16, 42, 851521)),
        ),
    ]
