# Generated by Django 4.2.4 on 2024-03-25 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0006_stopreport_alter_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 12, 50, 32, 780373)),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 9, 50, 32, 780373, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stopreport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 12, 50, 32, 781373), verbose_name='Начало простоя'),
        ),
        migrations.AlterField(
            model_name='stopreport',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 12, 50, 32, 781373), verbose_name='Окончание простоя'),
        ),
    ]
