# Generated by Django 4.2.4 on 2024-03-25 09:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0007_alter_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 9, 59, 52, 763156, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stopreport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 9, 59, 52, 763156, tzinfo=datetime.timezone.utc), verbose_name='Начало простоя'),
        ),
        migrations.AlterField(
            model_name='stopreport',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 9, 59, 52, 763156, tzinfo=datetime.timezone.utc), verbose_name='Окончание простоя'),
        ),
    ]
