# Generated by Django 4.2.4 on 2024-03-26 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0008_alter_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stopreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало простоя'),
        ),
        migrations.AlterField(
            model_name='stopreport',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Окончание простоя'),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=30, verbose_name='Вес')),
                ('batch', models.CharField(max_length=30, verbose_name='Номер партии')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата производства')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='manufacture.product')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производство',
            },
        ),
    ]
