# Generated by Django 4.2.4 on 2024-03-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
        ('manufacture', '0009_product_alter_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='main.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
