# Generated by Django 4.2.4 on 2024-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'Новое'), ('W', 'В работе'), ('C', 'Закрыто')], default='N', max_length=10)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('image', models.ImageField(blank=True, null=True, upload_to='appeals/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обращение гражданина',
                'verbose_name_plural': 'Обращения граждан',
            },
        ),
    ]
