# Generated by Django 4.2.4 on 2024-02-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Appeal',
        ),
    ]
