# Generated by Django 4.2.4 on 2024-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_rename_answer_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='kp_number',
            field=models.CharField(default=1234567890, max_length=35, verbose_name='Номер контейнерной площадки'),
            preserve_default=False,
        ),
    ]
