# Generated by Django 4.2.4 on 2024-02-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_appeal_kp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона заявителя'),
        ),
    ]
