# Generated by Django 4.2.4 on 2024-03-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0004_appeal_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='kp_number',
            field=models.CharField(max_length=50, verbose_name='Номер контейнерной площадки'),
        ),
    ]
