# Generated by Django 4.2.4 on 2024-03-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0005_alter_appeal_kp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ник пользователя')),
                ('uid', models.CharField(max_length=30, verbose_name='Chat ID пользователя')),
                ('bot_name', models.CharField(max_length=30, verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Пользваотель телеграм бота',
                'verbose_name_plural': 'Пользваотели телеграм бота',
            },
        ),
    ]
