# Generated by Django 4.2.4 on 2024-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0006_botuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь телеграм бота', 'verbose_name_plural': 'Пользователи телеграм бота'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
