# Generated by Django 4.2.4 on 2024-12-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
                ('url', models.CharField(max_length=155, verbose_name='URL')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(max_length=155, verbose_name='Номер автомобиля')),
                ('plate_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография номера')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография с камеры')),
                ('ratio', models.FloatField(default=0.0, verbose_name='Коэфициент распознавания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognitions', to='detection.camera')),
            ],
            options={
                'verbose_name': 'Распознавание',
                'verbose_name_plural': 'Распознавания',
            },
        ),
    ]
