# Generated by Django 4.2.4 on 2024-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
