# Generated by Django 4.2.4 on 2024-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_camera_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('confidence_threshold', models.FloatField(default=0, verbose_name='Чувствительность определения')),
                ('delay', models.IntegerField(default=0, verbose_name='Задержка для записи в БД')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='recognition',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фотография с камеры'),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='plates/', verbose_name='Фотография номера'),
        ),
    ]
