# Generated by Django 4.2.4 on 2024-12-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_remove_detectionsettings_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionsettings',
            name='plate_file',
            field=models.FileField(blank=True, null=True, upload_to='models/', verbose_name='Файл модели номера'),
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='symbol_file',
            field=models.FileField(blank=True, null=True, upload_to='models/', verbose_name='Файл модели знаков'),
        ),
    ]
