# Generated by Django 4.2.4 on 2024-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_detectionsettings_plate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='car_image',
            field=models.ImageField(upload_to='cars/', verbose_name='Фотография с камеры'),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='plate_image',
            field=models.ImageField(upload_to='plates/', verbose_name='Фотография номера'),
        ),
    ]
