# Generated by Django 4.2.4 on 2023-09-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование отчёта')),
                ('answer', models.BooleanField(default=False, verbose_name='Результат')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование отчёта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('company_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('question_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.question')),
                ('report_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.report')),
            ],
            options={
                'verbose_name': 'Данные отчёта',
                'verbose_name_plural': 'Данные отчётов',
            },
        ),
    ]
