# Generated by Django 4.2.4 on 2023-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Соответствие'),
        ),
    ]
