# Generated by Django 4.2.4 on 2023-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_alter_question_image_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='Соответствие'),
        ),
    ]
