# Generated by Django 4.2.4 on 2023-09-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0003_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdata',
            name='question_title',
        ),
        migrations.AddField(
            model_name='reportdata',
            name='question_title',
            field=models.ManyToManyField(to='labor.question'),
        ),
    ]
