# Generated by Django 4.2.4 on 2023-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0005_remove_question_answer_remove_question_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdata',
            name='question_title',
        ),
        migrations.AddField(
            model_name='reportdata',
            name='answer',
            field=models.ManyToManyField(to='labor.answer'),
        ),
    ]
