# Generated by Django 4.2.4 on 2023-09-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_alter_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='question_title',
            field=models.ManyToManyField(to='labor.question'),
        ),
    ]
