# Generated by Django 4.2.4 on 2023-09-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0008_report_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdata',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='report_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labor.reportdata'),
        ),
    ]
