# Generated by Django 4.2.4 on 2023-09-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_number'),
        ('labor', '0009_remove_reportdata_answer_answer_report_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportData',
            new_name='Checklist',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='report_data',
            new_name='checklist',
        ),
    ]
