# Generated by Django 4.2.4 on 2023-09-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0010_rename_reportdata_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checklist',
            name='answer',
            field=models.ManyToManyField(to='labor.answer'),
        ),
    ]
