# Generated by Django 4.2.4 on 2023-09-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0011_remove_answer_checklist_checklist_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='answer',
            new_name='answers',
        ),
    ]
