# Generated by Django 4.2.4 on 2023-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0012_rename_answer_checklist_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='Сдан'),
        ),
    ]
