# Generated by Django 4.2.4 on 2023-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0013_checklist_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
