# Generated by Django 4.2.4 on 2023-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0015_rename_question_title_report_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Чеклист', 'verbose_name_plural': 'Чеклисты'},
        ),
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
