# Generated by Django 4.2.4 on 2023-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0016_alter_checklist_options_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='questions',
            field=models.ManyToManyField(related_name='report', to='labor.question'),
        ),
    ]
