# Generated by Django 4.2.4 on 2023-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0017_alter_report_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='questions',
            field=models.ManyToManyField(related_name='reports', to='labor.question'),
        ),
    ]
