# Generated by Django 4.2.4 on 2023-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0018_alter_report_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='questions',
            field=models.ManyToManyField(to='labor.question'),
        ),
    ]
