# Generated by Django 4.2.4 on 2023-09-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0019_alter_report_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labor.report'),
        ),
    ]
