# Generated by Django 4.2.4 on 2023-09-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0020_remove_report_questions_question_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='labor.report'),
        ),
    ]
