# Generated by Django 4.2.4 on 2023-09-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_number'),
        ('labor', '0021_alter_question_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='car_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
    ]
