# Generated by Django 4.2.4 on 2023-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0022_alter_checklist_car_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='car_necessary',
            field=models.BooleanField(default=False, verbose_name='Результат'),
        ),
    ]
