# Generated by Django 4.2.4 on 2023-09-17 11:53

import django.core.validators
from django.db import migrations, models
import labor.models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0023_report_car_necessary'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='period_at',
            field=models.IntegerField(default=labor.models.current_year, validators=[django.core.validators.MinValueValidator(2020), labor.models.max_value_current_year], verbose_name='Год'),
        ),
    ]
