# Generated by Django 4.2.4 on 2023-09-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0027_alter_checklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='period',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
