# Generated by Django 4.2.4 on 2023-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0028_checklist_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='period',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
