# Generated by Django 4.2.4 on 2023-10-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0032_rename_result_answer_answer_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='report_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='labor.report'),
        ),
    ]
