# Generated by Django 4.2.4 on 2023-11-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_company'),
        ('labor', '0033_alter_checklist_report_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statictic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_answers_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ответы ДА')),
                ('no_answers_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ответы НЕТ')),
                ('empty_answers_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ответы ПУСТО')),
                ('company_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('report_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='labor.report')),
            ],
            options={
                'verbose_name': 'Статистический отчёт',
                'verbose_name_plural': 'Статистические отчёты',
            },
        ),
    ]
