# Generated by Django 4.2.4 on 2023-11-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_company'),
        ('labor', '0034_statictic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statictic',
            new_name='Statistic',
        ),
    ]
