# Generated by Django 4.2.4 on 2023-11-02 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0035_rename_statictic_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='period',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
