# Generated by Django 4.2.4 on 2023-11-02 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0036_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 12, 19, 56, 703957, tzinfo=datetime.timezone.utc)),
        ),
    ]
