# Generated by Django 4.2.4 on 2023-11-24 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0037_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='answers',
            field=models.ManyToManyField(related_name='checklists', to='labor.answer'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 15, 33, 35, 693401, tzinfo=datetime.timezone.utc)),
        ),
    ]
