# Generated by Django 4.2.4 on 2023-11-27 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0038_alter_checklist_answers_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 9, 35, 44, 715344, tzinfo=datetime.timezone.utc)),
        ),
    ]
