# Generated by Django 4.2.4 on 2023-11-27 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0039_alter_statistic_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='repiod_necessary',
            field=models.BooleanField(default=False, verbose_name='Добавить дату отчёта'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 9, 40, 48, 593451, tzinfo=datetime.timezone.utc)),
        ),
    ]
