# Generated by Django 4.2.4 on 2023-11-27 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0040_report_repiod_necessary_alter_statistic_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='repiod_necessary',
            new_name='period_necessary',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 9, 43, 0, 178519, tzinfo=datetime.timezone.utc)),
        ),
    ]
