# Generated by Django 4.2.4 on 2024-02-28 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0041_rename_repiod_necessary_report_period_necessary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 10, 59, 47, 536512, tzinfo=datetime.timezone.utc)),
        ),
    ]
