# Generated by Django 4.2.4 on 2024-02-28 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0042_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 11, 1, 22, 896253, tzinfo=datetime.timezone.utc)),
        ),
    ]
