# Generated by Django 4.2.4 on 2024-02-29 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0044_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 15, 25, 47, 254486, tzinfo=datetime.timezone.utc)),
        ),
    ]
