# Generated by Django 4.2.4 on 2024-03-03 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('labor', '0045_alter_statistic_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='reports', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 3, 12, 24, 43, 215756, tzinfo=datetime.timezone.utc)),
        ),
    ]
