# Generated by Django 4.2.4 on 2024-03-03 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0047_remove_report_groups_alter_statistic_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='groups',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 3, 12, 28, 27, 573719, tzinfo=datetime.timezone.utc)),
        ),
    ]
