# Generated by Django 4.2.4 on 2024-03-05 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0048_rename_groups_report_group_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 5, 11, 25, 57, 456752, tzinfo=datetime.timezone.utc)),
        ),
    ]
