# Generated by Django 4.2.4 on 2024-03-13 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0050_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 12, 13, 23, 806769, tzinfo=datetime.timezone.utc)),
        ),
    ]
