# Generated by Django 4.2.4 on 2024-03-18 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0052_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 10, 0, 34, 950046, tzinfo=datetime.timezone.utc)),
        ),
    ]
