# Generated by Django 4.2.4 on 2024-03-19 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0053_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 15, 29, 25, 486637, tzinfo=datetime.timezone.utc)),
        ),
    ]
