# Generated by Django 4.2.4 on 2024-03-22 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0056_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 13, 16, 42, 801537, tzinfo=datetime.timezone.utc)),
        ),
    ]
