# Generated by Django 4.2.4 on 2024-03-25 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0057_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 9, 50, 32, 731373, tzinfo=datetime.timezone.utc)),
        ),
    ]
