# Generated by Django 4.2.4 on 2024-03-26 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0060_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 12, 36, 5, 668568, tzinfo=datetime.timezone.utc)),
        ),
    ]
