# Generated by Django 4.2.4 on 2024-11-02 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0061_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 11, 2, 8, 29, 21, 592718, tzinfo=datetime.timezone.utc)),
        ),
    ]
