# Generated by Django 4.2.4 on 2024-11-12 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0066_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 9, 57, 5, 804325, tzinfo=datetime.timezone.utc)),
        ),
    ]
