# Generated by Django 4.2.4 on 2024-12-19 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0068_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 12, 19, 16, 4, 48, 761502, tzinfo=datetime.timezone.utc)),
        ),
    ]
