# Generated by Django 4.2.4 on 2024-12-21 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0069_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 12, 21, 14, 5, 24, 914183, tzinfo=datetime.timezone.utc)),
        ),
    ]
