# Generated by Django 4.2.4 on 2024-12-21 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0070_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 12, 21, 14, 6, 14, 96363, tzinfo=datetime.timezone.utc)),
        ),
    ]
