# Generated by Django 4.2.4 on 2024-12-21 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0072_alter_statistic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.DateField(default=datetime.datetime(2024, 12, 21, 15, 50, 55, 914514, tzinfo=datetime.timezone.utc)),
        ),
    ]
